# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="A fast, iteratee-based, epoll-enabled web server for the Snap Framework"
HOMEPAGE="http://snapframework.com/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/attoparsec-0.8.1
		<dev-haskell/attoparsec-0.9
		>=dev-haskell/attoparsec-iteratee-0.1.1
		<dev-haskell/attoparsec-iteratee-0.2
		dev-haskell/bytestring-nums
		>=dev-haskell/bytestring-show-0.3.2
		<dev-haskell/bytestring-show-0.4
		=dev-haskell/cereal-0.3*
		dev-haskell/directory-tree
		=dev-haskell/dlist-0.5*
		>=dev-haskell/iteratee-0.3.1
		<dev-haskell/iteratee-0.4
		dev-haskell/monads-fd
		=dev-haskell/murmur-hash-0.1*
		=dev-haskell/network-2.2.1*
		>=dev-haskell/network-bytestring-0.1.2
		<dev-haskell/network-bytestring-0.2
		=dev-haskell/psqueue-1.1*
		>=dev-haskell/snap-core-0.2.11
		<dev-haskell/snap-core-0.3
		dev-haskell/time
		dev-haskell/transformers
		dev-haskell/unix-compat
		=dev-haskell/vector-0.6*
		>=dev-lang/ghc-6.8.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
