# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Provides some basic WAI handlers and middleware."
HOMEPAGE="http://github.com/snoyberg/wai-extra"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/network-2.2.1.5
		<dev-haskell/network-2.3
		>=dev-haskell/sendfile-0.6.1
		<dev-haskell/sendfile-0.8
		>=dev-haskell/time-1.1.4
		<dev-haskell/time-1.3
		>=dev-haskell/utf8-string-0.3.4
		<dev-haskell/utf8-string-0.4
		>=dev-haskell/wai-0.2.0
		<dev-haskell/wai-0.3
		>=dev-lang/ghc-6.8.1
		sys-libs/zlib"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2"
