# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Push-pull functional reactive programming"
HOMEPAGE="http://haskell.org/haskellwiki/reactive"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE=""	#Fixme: "OtherLicense", please fill in manually
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/category-extras-0.53.5
		>=dev-haskell/checkers-0.2.3
		>=dev-haskell/quickcheck-2.1.0.2
		>=dev-haskell/stream-0.3.1
		>=dev-haskell/typecompose-0.8.0
		>=dev-haskell/unamb-0.1.5
		>=dev-haskell/vector-space-0.5
		>=dev-lang/ghc-6.8.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2"
