# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Provide versions of Either with good monad and applicative instances."
HOMEPAGE="http://github.com/snoyberg/neither"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/failure-0.1.0
		<dev-haskell/failure-0.2
		>=dev-haskell/monadcatchio-mtl-0.3.0.1
		<dev-haskell/monadcatchio-mtl-0.4
		>=dev-haskell/monadcatchio-transformers-0.2.2
		<dev-haskell/monadcatchio-transformers-0.3
		>=dev-haskell/mtl-1.1.0.2
		<dev-haskell/mtl-1.2
		>=dev-haskell/transformers-0.2.1
		<dev-haskell/transformers-0.3
		>=dev-lang/ghc-6.8.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
