# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="bin lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Creation of type-safe, RESTful web applications."
HOMEPAGE="http://docs.yesodweb.com/yesod/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/authenticate-0.6.3
		<dev-haskell/authenticate-0.7
		=dev-haskell/blaze-builder-0.1*
		=dev-haskell/cereal-0.2*
		>=dev-haskell/clientsession-0.4.0
		<dev-haskell/clientsession-0.5
		=dev-haskell/control-monad-attempt-0.3*
		>=dev-haskell/data-object-0.3.1
		<dev-haskell/data-object-0.4
		>=dev-haskell/dataenc-0.13.0.2
		<dev-haskell/dataenc-0.14
		>=dev-haskell/email-validate-0.2.5
		<dev-haskell/email-validate-0.3
		>=dev-haskell/hamlet-0.5.0
		<dev-haskell/hamlet-0.6
		>=dev-haskell/monadcatchio-transformers-0.2.2.0
		<dev-haskell/monadcatchio-transformers-0.3
		>=dev-haskell/neither-0.0.0
		<dev-haskell/neither-0.1
		>=dev-haskell/network-2.2.1.5
		<dev-haskell/network-2.3
		>=dev-haskell/parsec-2.1
		<dev-haskell/parsec-4
		>=dev-haskell/persistent-0.2.0
		<dev-haskell/persistent-0.3
		>=dev-haskell/puremd5-1.1.0.0
		<dev-haskell/puremd5-1.2
		>=dev-haskell/text-0.5
		<dev-haskell/text-0.9
		>=dev-haskell/time-1.1.4
		<dev-haskell/time-1.3
		=dev-haskell/transformers-0.2*
		>=dev-haskell/utf8-string-0.3.4
		<dev-haskell/utf8-string-0.4
		>=dev-haskell/wai-0.2.0
		<dev-haskell/wai-0.3
		>=dev-haskell/wai-extra-0.2.2
		<dev-haskell/wai-extra-0.3
		=dev-haskell/web-routes-quasi-0.6*
		>=dev-lang/ghc-6.8.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
