# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.9

CABAL_FEATURES="bin lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Haml-like template files that are compile-time checked"
HOMEPAGE="http://docs.yesodweb.com/hamlet/"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/blaze-builder-0.1*
		>=dev-haskell/failure-0.1.0
		<dev-haskell/failure-0.2
		>=dev-haskell/neither-0.0.1
		<dev-haskell/neither-0.1
		>=dev-haskell/parsec-2
		<dev-haskell/parsec-4
		>=dev-haskell/utf8-string-0.3.4
		<dev-haskell/utf8-string-0.4
		>=dev-lang/ghc-6.8.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
